### ISSUE TITLE
How to choose / streaming resolution?

### ISSUE THREAD

**Issue by thamz88** [lylehust/Chinese-IPTV#2]
Hi. Thanks for sharing the playlist. I tried using it on Kodi and it's working fine but there are several channels cannot be played. Apart from that, is there any how to set the streaming into 720p or auto streaming due to internet connection? My internet is not that fast and a bit lagging when streaming into 1080p. I tried force resolution streaming into 7209 or 480p on Kodi PVR but not working. It's always back into 1080p.  By the way, can you add Zhe Jiang TV as well? Looking forward for a solution. Thank you for your help

**Comment by lylehust** [comment]
Can not change resolution.
